# Nome da sua pipeline, que vai aparecer no GitHub
name: Pipeline de Segurança DevSecOps

# Define o gatilho: essa pipeline vai rodar sempre que você fizer um 'push' para a branch 'main'
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Define os 'jobs' ou tarefas que a pipeline vai executar
jobs:
  scans-de-seguranca:
    # A pipeline vai rodar em uma máquina virtual do GitHub com a última versão do Ubuntu
    runs-on: ubuntu-latest

    steps:
    # Passo 1: Clona o seu repositório para a máquina virtual
    - name: Checkout do código
      uses: actions/checkout@v3

    # =================================================================
    # TÉCNICA 1: ANÁLISE DE VULNERABILIDADES NA IMAGEM (Container Scanning)
    # Ferramenta: Trivy
    # =================================================================
    - name: Scan da imagem Docker com Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'bkimminich/juice-shop'
        format: 'table'
        exit-code: '0'
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH'

    # =================================================================
    # TÉCNICA 2: ANÁLISE DE DEPENDÊNCIAS (SCA - Software Composition Analysis)
    # Ferramenta: Anchore/Syft
    # =================================================================
    - name: Scan de Dependências com Anchore Scan
      uses: anchore/scan-action@v3
      with:
        image: 'bkimminich/juice-shop'
        fail-build: false
        severity-cutoff: high

    # =================================================================
    # TÉCNICA 3: ANÁLISE ESTÁTICA DO CÓDIGO (SAST - Static Application Security Testing)
    # Ferramenta: SonarCloud
    # =================================================================
    - name: Scan de Código com SonarCloud
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=cesar-devsecops2025
          -Dsonar.projectKey=cesar-devsecops2025_projeto-final-devsecops